AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:

    ServiceDeskOperationsDynamoTable:
      Type: AWS::DynamoDB::Table
      UpdateReplacePolicy: Retain
      DeletionPolicy: Retain
      Properties:
        TableName: !Sub '${ProjectName}-PnServiceDeskOperations'
        AttributeDefinitions:
          - AttributeName: "operationId"
            AttributeType: "S"
          - AttributeName: "recipientInternalId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "operationId"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: "recipientInternalId-index"
            KeySchema:
              - AttributeName: "recipientInternalId"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
        KinesisStreamSpecification:
          StreamArn: !Ref CdcKinesisSourceStreamArn
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: "PAY_PER_REQUEST"
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    ServiceDeskAddressDynamoTable:
      Type: AWS::DynamoDB::Table
      UpdateReplacePolicy: Retain
      DeletionPolicy: Retain
      Properties:
        TableName: !Sub '${ProjectName}-PnServiceDeskAddress'
        AttributeDefinitions:
          - AttributeName: "operationId"
            AttributeType: "S"
        TimeToLiveSpecification:
          AttributeName: "ttl"
          Enabled: true
        KeySchema:
          - AttributeName: "operationId"
            KeyType: "HASH"
        KinesisStreamSpecification:
          StreamArn: !Ref CdcKinesisSourceStreamArn
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: "PAY_PER_REQUEST"
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    ServiceDeskOperationFileKeyDynamoTable:
      Type: AWS::DynamoDB::Table
      UpdateReplacePolicy: Retain
      DeletionPolicy: Retain
      Properties:
        TableName: !Sub '${ProjectName}-PnServiceDeskOperationFileKey'
        AttributeDefinitions:
          - AttributeName: "fileKey"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "fileKey"
            KeyType: "HASH"
        KinesisStreamSpecification:
          StreamArn: !Ref CdcKinesisSourceStreamArn
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: "PAY_PER_REQUEST"
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    PCKmsEncDecDynamoDataKey:
      Type: 'AWS::KMS::Key'
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        Description: A symmetric encryption KMS key AES-256-GCM
        KeySpec: SYMMETRIC_DEFAULT
        KeyUsage: ENCRYPT_DECRYPT
        KeyPolicy:
          Version: 2012-10-17
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: Allow
              Principal:
                AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
              Action: 'kms:*'
              Resource: '*'
    PCKmsEncDecDynamoDataKeyAlias:
      Type: 'AWS::KMS::Alias'
      Properties:
        AliasName: !Sub 'alias/${ProjectName}-paper-channel-dynamo'
        TargetKeyId: !Ref PCKmsEncDecDynamoDataKey

Outputs:

    ServiceDeskOperationsDynamoTableName:
      Description: Name of dynamodb table containing request
      Value: !Ref ServiceDeskOperationsDynamoTable

    ServiceDeskOperationsDynamoTableArn:
      Description: ARN of dynamodb table containing request
      Value: !Sub '${ServiceDeskOperationsDynamoTable.Arn}'

    ServiceDeskAddressDynamoTableName:
      Description: Name of dynamodb table containing request
      Value: !Ref ServiceDeskAddressDynamoTable

    ServiceDeskAddressDynamoTableArn:
      Description: ARN of dynamodb table containing request
      Value: !Sub '${ServiceDeskAddressDynamoTable.Arn}'

    ServiceDeskOperationFileKeyDynamoTableName:
      Description: Name of dynamodb table containing request
      Value: !Ref ServiceDeskOperationFileKeyDynamoTable

    ServiceDeskOperationFileKeyDynamoTableArn:
      Description: ARN of dynamodb table containing request
      Value: !Sub '${ServiceDeskOperationFileKeyDynamoTable.Arn}'

    PCKmsEncDecDynamoDataKeyARN:
      Description: Name of KMS Key for Dynamo encode/decode data
      Value: !Sub '${PCKmsEncDecDynamoDataKey.Arn}'