AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
    NullResource:
        Type: AWS::CloudFormation::WaitConditionHandle
    PCKmsEncDecDynamoDataKey:
      Type: 'AWS::KMS::Key'
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        Description: A symmetric encryption KMS key AES-256-GCM
        KeySpec: SYMMETRIC_DEFAULT
        KeyUsage: ENCRYPT_DECRYPT
        KeyPolicy:
          Version: 2012-10-17
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: Allow
              Principal:
                AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
              Action: 'kms:*'
              Resource: '*'
    PCKmsEncDecDynamoDataKeyAlias:
      Type: 'AWS::KMS::Alias'
      Properties:
        AliasName: !Sub 'alias/${ProjectName}-paper-channel-dynamo'
        TargetKeyId: !Ref PCKmsEncDecDynamoDataKey

Outputs:
    SampleOutput:
      Description: A Sample Output
      Value: 'na'

    PCKmsEncDecDynamoDataKeyARN:
      Description: Name of KMS Key for Dynamo encode/decode data
      Value: !Sub '${PCKmsEncDecDynamoDataKey.Arn}'