openapi: 3.0.1
info:
  title: >-
    ${stageVariables.ProjectName}-${stageVariables.MicroServiceUniqueName}-${stageVariables.IntendedUsage}
  version: QyolE2YwAD1hNpM8EfR1X6SovtQRM/5f2PHifD7Cl/k=
servers:
  - url: https://${stageVariables.DnsName}/{basePath}
    variables:
      basePath:
        default: /${stageVariables.ServiceApiPath}
    x-amazon-apigateway-endpoint-configuration:
      disableExecuteApiEndpoint: true
paths: {}
components:
  parameters:
    cxOperatorClientAuthFleet:
      name: x-pagopa-pn-uid
      in: header
      description: User Identifier
      required: true
      schema:
        type: string
        pattern: ^[ -~]*$
        minLength: 1
        maxLength: 64
  schemas:
    NotificationRequest:
      description: >-
        Request per la verifica della presenza di notifiche in stato
        irreperibile
      type: object
      properties:
        taxId:
          type: string
          format: /[^A-Za-z0-9]+/
          maxLength: 32
      additionalProperties: false
    NotificationsUnreachableResponse:
      description: >-
        Reponse che ritorna 1 in caso di presenza di notifiche in stato
        irreperibile, altrimenti 0
      type: object
      required:
        - notificationsCount
      properties:
        notificationsCount:
          type: number
          maximum: 1
          minimum: 0
      additionalProperties: false
    CreateOperationRequest:
      required:
        - taxId
        - address
        - ticketId
      type: object
      properties:
        address:
          $ref: '#/components/schemas/AnalogAddress'
        taxId:
          type: string
          maxLength: 32
        ticketId:
          type: string
          format: /[^A-Za-z0-9]+/
          maxLength: 32
        ticketOperationId:
          type: string
          format: /[^A-Za-z0-9]+/
          maxLength: 10
      additionalProperties: false
    OperationsResponse:
      description: Reponse della creazione di un'operation
      type: object
      properties:
        operationId:
          type: string
          format: /[^A-Za-z0-9~]+/
          maxLength: 99999
          description: >-
            identificativo dell'operation appena creata sarà costituito da
            _ticketId_ e _ticketOperationId_ separati dal carattere "~" se 
            _ticketOperationId_ non è stato specificato allora l'operationId
            coinciderà con il _ticketId_
      additionalProperties: false
    VideoUploadRequest:
      description: Request per l'upload
      type: object
      properties:
        preloadIdx:
          title: Id della richiesta di precaricamento di un file
          description: >-
            Identificativo univoco all'interno della request HTTP, serve per
            correlare la risposta.
          type: string
        sha256:
          type: string
          format: /[^A-Za-z0-9]+/
          maxLength: 99999
          description: SHA256 del contenuto del file.
        contentType:
          type: string
          maxLength: 99999
          description: Il MIME format del contenuto del file che si intende caricare
          example: application/octet-stream
      additionalProperties: false
    VideoUploadResponse:
      description: Response della richiesta di upload
      type: object
      properties:
        url:
          type: string
          maxLength: 99999
          example: >-
            https://presignedurldemo.s3.eu-west-2.amazonaws.com/image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...
        fileKey:
          type: string
          maxLength: 99999
          example: PN_SERVICE_DESK_RECORDING-{UID}
        secret:
          type: string
          maxLength: 99999
          example: alow22ddw
      additionalProperties: false
    SearchNotificationRequest:
      required:
        - taxId
      type: object
      properties:
        taxId:
          type: string
          maxLength: 32
      additionalProperties: false
    SearchResponse:
      description: Response della search
      type: object
      properties:
        operations:
          type: array
          minItems: 0
          maxItems: 999999999
          items:
            $ref: '#/components/schemas/OperationResponse'
      additionalProperties: false
    NotificationStatus:
      required:
        - status
      type: object
      properties:
        status:
          type: string
          description: >
            * `CREATING` - Operazione in attesa di caricamento del video *
            `VALIDATION` - Operazione in fase di validazione di indirizzo e
            allegati * `PREPARING` - Operazione in fase di preparazione di invio
            * `PROGRESS` - Operazione in fase di processamento della spedizione
            * `OK` - Notifica recapitata   * `KO` - Notifica in errore di
            spedizione o in errore di validazione
          enum:
            - CREATING
            - VALIDATION
            - PREPARING
            - PROGRESS
            - OK
            - KO
        statusCode:
          type: string
          maxLength: 99999
          description: codice dello stato dell'operazione
        statusDescription:
          type: string
          maxLength: 99999
          description: descrizione dello stato dell'operazione
        lastEventTimestamp:
          type: string
          format: date-time
      additionalProperties: false
    OperationResponse:
      required:
        - operationId
        - taxId
        - notificationStatus
        - operationCreateTimestamp
        - operationUpdateTimestamp
      properties:
        operationId:
          type: string
        taxId:
          type: string
          maxLength: 32
        iuns:
          type: array
          minItems: 1
          maxItems: 999999999
          items:
            $ref: '#/components/schemas/SDNotificationSummary'
        uncompletedIuns:
          type: array
          minItems: 1
          maxItems: 999999999
          items:
            $ref: '#/components/schemas/SDNotificationSummary'
        notificationStatus:
          $ref: '#/components/schemas/NotificationStatus'
        operationCreateTimestamp:
          type: string
          format: date-time
          description: Timestamp della richiesta in UTC
        operationUpdateTimestamp:
          type: string
          format: date-time
          description: Timestamp della richiesta in UTC
    AnalogAddress:
      required:
        - address
        - city
        - fullname
        - cap
      properties:
        fullname:
          type: string
          maxLength: 99999
          description: Cognome e nome o ragione sociale del destinatario
        nameRow2:
          type: string
          maxLength: 99999
          description: Seconda riga sulla busta.
        address:
          type: string
          maxLength: 99999
          description: Indirizzo del destinatario.
        addressRow2:
          type: string
          maxLength: 99999
          description: >-
            Specifica dell’indirizzo di residenza del destinatario (seconda riga
            indirizzo sulla busta).
        cap:
          type: string
          maxLength: 99999
          description: Cap del destinatario; in caso di invio estero diventa facoltativo.
        city:
          type: string
          maxLength: 99999
          description: Comune del destinatario.
        city2:
          type: string
          maxLength: 99999
          description: >-
            Frazione del destinatario. Potrebbe essere utile se il chiamante non
            fornisce il cap.
        pr:
          type: string
          maxLength: 99999
          description: >-
            Provincia del destinatario; in caso di invio estero diventa
            facoltativo.
        country:
          type: string
          maxLength: 99999
          description: >-
            In caso di destinatario estero, diventa obbligatoria l’indicazione
            della nazione di destinazione,  in standard UPU o altro standard
            condiviso.
      description: Indirizzo analogico
    SDNotificationSummary:
      type: object
      required:
        - iun
        - senderPaInternalId
        - senderPaDescription
      properties:
        iun:
          type: string
          maxLength: 99999
        senderPaInternalId:
          type: string
          description: Identificativo Selfcare della PA mittente
          maxLength: 99999
        senderPaDescription:
          type: string
          maxLength: 99999
          description: Descrizione breve della PA mittente
        senderPaIpaCode:
          type: string
          maxLength: 99999
          description: Codice IPA della PA mittente
        senderPaTaxCode:
          type: string
          maxLength: 99999
          description: Codice Fiscale della PA mittente
  responses: {}
  securitySchemes:
    api_key_openapi:
      type: apiKey
      name: x-api-key
      in: header
    pn-auth-fleet_ApiKeyAuthorizerV2_openapi:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerUri: >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:pn-ApiKeyAuthorizerV2Lambda/invocations
        authorizerResultTtlInSeconds: 60
        identitySource: method.request.header.x-api-key
        type: request
tags:
  - null
x-amazon-apigateway-gateway-responses:
  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: '''*'''
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: '''*'''
  BAD_REQUEST_PARAMETERS:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: '''*'''
    responseTemplates:
      application/json: >-
        {"status": 400, "title": "VALIDATION ERROR", "traceId":
        "$context.xrayTraceId", "errors": [ { "code": "PN_INVALID_PARAMETERS",
        "detail": "Validation errors: $context.error.validationErrorString" } ]}
  BAD_REQUEST_BODY:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: '''*'''
    responseTemplates:
      application/json: >-
        {"status": 400, "title": "VALIDATION ERROR", "traceId":
        "$context.xrayTraceId", "errors": [ { "code": "PN_INVALID_BODY",
        "detail": "Validation errors: $context.error.validationErrorString" } ]}
x-amazon-apigateway-request-validators:
  basic:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
x-amazon-apigateway-request-validator: basic
